### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Icehunter**
Reopening PR; this fixes the issue in #16

### CODE REVIEW

**Comment by Icehunter** [comment]
@shama Does this update fall inline with your coding style so that it can work again? For some reason the changes in 0.3.0 broke for a number of people.

Thanks!

**Comment by sokra** [comment]
`CompressionOptions` should be an instance variable not a static variable...

**Comment by Icehunter** [comment]
@sokra Updated :)

**Comment by robbyoconnor** [comment]
Is this gonna be merged -- or is this just project not maintained?

**Comment by andersonba** [comment]
:+1:

**Comment by mathieumg** [comment]
:+1:

**Comment by mathieumg** [comment]
@sokra Is anything blocking this?

**Comment by sokra** [comment]
@mathieumg no ;)

**Pull request merged**
