### PR TITLE
added brotli support via iltorb

### PR DESCRIPTION
**Pull request by mynameiswhm**

### CODE REVIEW

**Comment by mynameiswhm** [comment]
what's up with default travis configuration? :)

**Comment by palmerj3** [comment]
@mynameiswhm thank you!

I'm a bit uncomfortable adding an additional optionalDependency. TBH I don't like that we have an optionalDependency already for node-zopfli. Unless there is a failure of install you are guaranteed to add ~8mb to the bundle. I'll leave this open for now and ask for others to comment so I know what kind of support this has.

My opinion is that each unique compression should be a separate compression plugin instead of this plugin providing a factory-like interface to a bunch of optional dependencies.

**Comment by mynameiswhm** [comment]
@palmerj3 fair enough, that's kind of makes sense!

I think i'm going to make a separate plugin for this tomorrow, but yeah,let's hear another maintainers' opinions :)

**Comment by mynameiswhm** [comment]
ok, I've created [brotli-webpack-plugin](https://github.com/ngsru/brotli-webpack-plugin), closing the pull request!

**Pull request closed without merging**
